### ISSUE TITLE
The "Usage" fail

### ISSUE THREAD

**Issue by dkostenko** [nielstron/quantulum3#95]
I tried to use library with this manual (https://github.com/nielstron/quantulum3#usage) and got an error: ModuleNotFoundError: No module named 'quantulum3._lang.en_US.parser'

Trace:
```
>>> parser.parse('I want 2 liters of wine')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/quantulum3/parser.py", line 433, in parse
    text = clean_text(text, lang)
  File "/usr/local/lib/python3.7/site-packages/quantulum3/parser.py", line 408, in clean_text
    text = _get_parser(lang).clean_text(text)
  File "/usr/local/lib/python3.7/site-packages/quantulum3/parser.py", line 28, in _get_parser
    return language.get('parser', lang)
  File "/usr/local/lib/python3.7/site-packages/quantulum3/language.py", line 52, in get
    '{}._lang.{}.{}'.format(__package__, subdir(lang), module)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'quantulum3._lang.en_US.parser'
```

**Comment by nielstron** [comment]
Finally found the error, should be fixed with the next version release.
